### ISSUE TITLE
Support Editing Customer Credit Cards

### ISSUE THREAD

**Issue by jme783** [ride/ember-stripe-service#34]
While this library works for creating a Stripe token for a card, there's no way to edit a credit card. I need this feature for allowing users to correct expired/failing credit cards

**Comment by buritica** [comment]
hey @jme783 you're not supposed to edit cards using stripe.js in the client side, check out https://stripe.com/docs/api#update_card.

stripe.js is only meant to let you capture a card in the frontend, create a token, and then be able to relate the card token with your customer in the backend to maintain PCI compliance
