### ISSUE TITLE
isDevelopingAddon is true

### ISSUE THREAD

**Issue by jamesarosen** [ride/ember-stripe-service#43]
This should be `false` in released Ember addons.

See https://github.com/dockyard/ember-suave/issues/67 and https://github.com/ember-animation/liquid-fire/issues/383.

**Comment by jamesarosen** [comment]
Introduced in [797471e4](https://github.com/ride/ember-stripe-service/commit/797471e4d937ff1bc2566b8a3fe3af3b4f421603#diff-168726dbe96b3ce427e7fedce31bb0bcR14) by @samselikoff

**Comment by buritica** [comment]
thanks for the catch, I missed it completely. This is live now

**Comment by jamesarosen** [comment]
That's some impressively fast turnaround :)

**Comment by buritica** [comment]
we don't like bugs in production

**Comment by samselikoff** [comment]
woops, and thanks! 🎩
